#!/bin/bash
# Portfolio Website - Quick Setup Script

echo "🚀 PORTFOLIO WEBSITE - QUICK SETUP"
echo "=================================="
echo ""
echo "📋 PREREQUISITES:"
echo "   1. Node.js v14+ installed"
echo "   2. Supabase account created (free at supabase.com)"
echo "   3. Your Supabase URL & anon key"
echo ""
echo "📁 YOUR FOLDER STRUCTURE:"
echo "   Portfolio Website/"
echo "   ├── frontend/"
echo "   │   ├── index.html ✅"
echo "   │   ├── style.css ✅"
echo "   │   └── script.js ✅"
echo "   ├── backend/"
echo "   │   ├── server.js ✅"
echo "   │   ├── package.json ✅"
echo "   │   ├── .env (FILL THIS)"
echo "   │   └── routes/"
echo "   │       ├── projects.js ✅"
echo "   │       └── contact.js ✅"
echo "   └── Documentation/guides (5 files)"
echo ""
echo "⚡ QUICK SETUP (7 MINUTES):"
echo ""
echo "STEP 1 - Supabase Setup (2 min)"
echo "   □ Create account: https://supabase.com"
echo "   □ Create 2 tables (SQL provided in guides)"
echo "   □ Add 3+ sample projects"
echo "   □ Get: Project URL + Anon Key"
echo ""
echo "STEP 2 - Backend Setup (2 min)"
echo "   □ Edit backend/.env with credentials"
echo "   □ Run: cd backend && npm install"
echo "   □ Run: npm run dev"
echo ""
echo "STEP 3 - Frontend Setup (1 min)"
echo "   □ Right-click frontend/index.html"
echo "   □ Select 'Open with Live Server'"
echo ""
echo "STEP 4 - Test (2 min)"
echo "   □ Navigate: Click nav links"
echo "   □ Projects: Should display from database"
echo "   □ Form: Submit contact form"
echo ""
echo "✨ FEATURES INCLUDED:"
echo "   ✅ Responsive Design (Mobile + Desktop)"
echo "   ✅ Smooth Scrolling Navigation"
echo "   ✅ Dynamic Project Cards"
echo "   ✅ Contact Form with Validation"
echo "   ✅ Database Integration (Supabase)"
echo "   ✅ RESTful Backend API"
echo "   ✅ Error Handling"
echo "   ✅ Modern UI with Animations"
echo ""
echo "📚 DOCUMENTATION:"
echo "   • START_HERE.md ..................... Overview (read first)"
echo "   • QUICK_START.md ................... 5-minute setup"
echo "   • IMPLEMENTATION_GUIDE.md .......... Full reference (200 lines)"
echo "   • SETUP_GUIDE.md ................... Detailed instructions"
echo "   • README.md ........................ Project features"
echo ""
echo "🔗 IMPORTANT URLS:"
echo "   Frontend: http://localhost:5500"
echo "   Backend:  http://localhost:3000"
echo "   API:      http://localhost:3000/api/projects"
echo ""
echo "📞 NEED HELP?"
echo "   1. Check browser console (F12)"
echo "   2. Check backend terminal for errors"
echo "   3. Read IMPLEMENTATION_GUIDE.md troubleshooting section"
echo "   4. Verify Supabase credentials in backend/.env"
echo ""
echo "🎉 YOU'RE READY TO GO!"
echo "=================================="
